---
version: '3.8'
services:
  # First image - "hello-world" with 5 nodes
  hello-world:
    image: hello-world
    deploy:
      mode: replicated
      replicas: 5

  # Third image - PostgreSQL database
  db:
    image: postgres:14.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Second image - Spring Boot application
  spring-app:
    image: gsadowski69/gs-spring-boot-app:1
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DEVOPS: GrzegorzSadowski
    ports:
      - "8080:8080"
